/* This file automatically generated by configure.  */

#define HAVE_ASPRINTF
#define HAVE_CONFSTR
#define HAVE_CURSES
#define HAVE_PLEDGE
#define HAVE_REALLOCARRAY
#define HAVE_SETRESGID
#define HAVE_SETRESUID
#define HAVE_SIG_T
#define HAVE_SRAND_DETERMINISTIC
#define HAVE_ST_MTIM
#define HAVE_ST_MTIMESPEC
#define HAVE_STRAVIS
#define HAVE_STRLCAT
#define HAVE_STRLCPY
#define HAVE_STRTONUM
#define HAVE_STRUNVIS
#define HAVE_SIGLIST
#define HAVE_SIGNAME
#define HAVE_TIMERADD
#define HAVE_TIMERSUB
